N1 = float(input('Largura da parede: '))
N2 = float(input('Altura da parade: '))
Area = (N1*N2)
print('Sua parede tem a dimensão de {}x{} e a sua área é de {}m²'.format(N1,N2,Area))
print('Para pintar sua parede, você ira precisar de {}l de tinda'.format(Area/2))