a = input('Digite algo')
print('O tipo primitivo é',type(a))
print('Só tem espaços?',a.isspace())
print('É um número?',a.isnumeric())
print('É alfabético?',a.isalpha())
print('É alfanumérico?',a.isalnum())
print('É Minusculo?',a.islower())
print('É Munisculo?',a.isupper())
print('É Capitalizada?',a.istitle())
